Update tutorial.md
open-spaced-repetition/fsrs4anki pull request #556
Opened 2023-12-09 16:52 UTC by Expertium

2023-12-09 18:26 UTC, Expertium commented
@user1823 check if everything is good

2023-12-10 03:15 UTC, user1823 requested changes

2023-12-10 03:15 UTC, user1823 commented on docs/tutorial.md
>  You haven't seen the answer for your question? Here are many questions asked by others: https://github.com/open-spaced-repetition/fsrs4anki/issues?q=is%3Aissue+label%3Aquestion+
```suggestion
Didn't find the answer to your question? You can browse through several other questions asked by users: https://github.com/open-spaced-repetition/fsrs4anki/issues?q=is%3Aissue+label%3Aquestion+
```

2023-12-10 03:15 UTC, user1823 commented on docs/tutorial.md
> +https://github.com/open-spaced-repetition/fsrs4anki/issues/new/choose
```suggestion
Is your issue still unsolved? Please open a new issue to provide the details: https://github.com/open-spaced-repetition/fsrs4anki/issues/new/choose
```

2023-12-10 03:15 UTC, user1823 commented on docs/tutorial.md
> +A4: FSRS only takes into account one review per day. If you review a card multiple times per day, only the chronologically first review will be used by the optimizer. Also, if your deck has many subd
```suggestion
A4: FSRS only takes into account one review per day. If you review a card multiple times per day, only the chronologically first review will be used by the optimizer. Also, if your deck has many subdecks, ensure that the preset is also applied to the subdecks, not just to the parent deck.
```

2023-12-10 06:26 UTC, L-M-Sherlock approved these changes

2023-12-10 06:27 UTC, merged